baseURL = 'https://bigmola.studio/'
locale = 'en-gb'
title = 'Big Mola Studio'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[module]
  [[module.imports]]
    path = 'github.com/nunocoracao/blowfish/v2'

[params]
  colorScheme = "big-mola"
  defaultAppearance = "dark"
